/**
 * Service to handle exporting repository analysis
 */
export const exportReport = (data) => {
  const report = {
    repository: data.repoId,
    url: data.repoUrl,
    analyzedAt: data.analyzedAt,
    metadata: data.metadata,
    metrics: data.metrics,
    summary: data.summary,
    architecture: data.architecture,
    hotspots: data.hotspots,
    techStack: data.techStack,
    recentHistory: data.history?.slice(0, 10),
    topChurnFiles: data.churn?.slice(0, 5)
  };

  const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `repolens-analysis-\${data.metadata.name}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportToMarkdown = (data) => {
  const md = `
# RepoLens Analysis: \${data.metadata.name}
Analyzed at: \${new Date(data.analyzedAt).toLocaleString()}

## 📋 Overview
\${data.summary.purpose}

**Tech Stack:** \${data.techStack.languages.join(', ')} | \${data.techStack.frameworks.join(', ')}

## 🏛️ Architecture
\${data.architecture.dataFlow}

### Key Components
\${data.architecture.directories.map(d => `- **\${d.path}**: \${d.description}`).join('\n')}

## 🚦 Code Health
**Total Files:** \${data.metrics.totalFiles}
**Total LOC:** \${data.metrics.totalLOC}
**Avg Complexity:** \${data.metrics.avgComplexity}

### ⚠️ Hotspots
\${data.hotspots.hotspots.map(h => `- **\${h.file}**: \${h.reason} (Risk: \${h.risk})`).join('\n')}

---
Generated by RepoLens AI
  `;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `repolens-report-\${data.metadata.name}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
